require "user.launch"
require "user.keymaps"
require "user.options"
require "plugins.autocmd"
-- spec "plugins.alpha"
-- spec "plugins.colorscheme"
spec "plugins.catppuccin"
spec "plugins.devicons"
spec "plugins.treesitter"
spec "plugins.mason"
spec "plugins.schemastore"
spec "plugins.telescope"
spec "plugins.lspconfig"
spec "plugins.cmp"
-- spec "plugins.none-ls"
spec "plugins.conform"
spec "plugins.whichkey"
spec "plugins.nvimtree"
spec "plugins.comment"
spec "plugins.navic"
spec "plugins.breadcrumbs"
spec "plugins.lualine"
spec "plugins.harpoon"
spec "plugins.illuminate"
spec "plugins.neotest"
spec "plugins.autopairs"
spec "plugins.neogit"
spec "plugins.project"
spec "plugins.indentline"
spec "plugins.toggleterm"
spec "plugins.debug"
spec "plugins.tmux"
-- extra
-- spec "plugins.extra.copilot"
spec "plugins.extra.live-server"
spec "plugins.extra.coderunner"
spec "plugins.extra.neoscroll"
spec "plugins.extra.oil"
spec "plugins.extra.ufo"
spec "plugins.extra.lab"
-- spec "plugins.extra.cellular-automaton"
-- spec "plugins.extra.eyeliner"
spec "plugins.extra.flash"
spec "plugins.extra.neotab"
-- spec "plugins.extra.tabnine"
spec "plugins.extra.fidget"
spec "plugins.extra.bqf"
spec "plugins.extra.modicator"
spec "plugins.extra.navbuddy"
spec "plugins.extra.move"
spec "plugins.extra.colorizer"
require "user.lazy"
